# Generated by Django 5.2.1 on 2025-05-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='v1.0', max_length=50)),
                ('trained_date', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'model_info_member1',
                'managed': True,
            },
        ),
    ]
