# Generated by Django 5.2.1 on 2025-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member1', '0002_modelinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelinfo',
            options={},
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='model_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='training_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='modelinfo',
            table=None,
        ),
    ]
