# Generated by Django 5.2 on 2025-05-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('enroll_id', models.IntegerField()),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'assessment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('enroll_id', models.IntegerField()),
                ('attendance_percentage', models.FloatField()),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('course_instructor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('semester_id', models.IntegerField()),
            ],
            options={
                'db_table': 'course_instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enroll_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('semester_id', models.IntegerField()),
                ('grade', models.FloatField()),
            ],
            options={
                'db_table': 'enrollment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_file', models.CharField(max_length=255)),
                ('training_data', models.CharField(max_length=255)),
                ('training_date', models.DateTimeField()),
                ('model_summary', models.TextField(blank=True)),
            ],
        ),
    ]
