# Generated by Django 4.2.21 on 2025-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalexampredict', '0002_course_delete_assessment_delete_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinfo',
            name='creator',
            field=models.CharField(default='maheswari', max_length=100),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='model_type',
            field=models.CharField(choices=[('classification', 'Classification'), ('clustering', 'Clustering'), ('regression', 'Regression')], default='classification', max_length=50),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='use_case',
            field=models.CharField(default='courses performance prediction', max_length=100),
        ),
    ]
