# Generated by Django 4.2.21 on 2025-05-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalexampredict', '0003_modelinfo_creator_modelinfo_model_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinfo',
            name='model_type',
            field=models.CharField(choices=[('classification', 'Classification'), ('clustering', 'Clustering'), ('regression', 'Regression')], default='clustering', max_length=50),
        ),
    ]
