# Generated by Django 4.2.21 on 2025-05-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalexampredict', '0004_alter_modelinfo_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attendance_percentage', models.FloatField()),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
    ]
