# Generated by Django 4.2.21 on 2025-05-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('semester_name', models.CharField(max_length=20)),
                ('attendance_percentage', models.FloatField()),
                ('midterm', models.FloatField()),
                ('final', models.FloatField()),
                ('project', models.FloatField()),
                ('average_score', models.FloatField()),
            ],
            options={
                'unique_together': {('student_id', 'semester_name')},
            },
        ),
    ]
