# Generated by Django 5.2 on 2025-05-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altara', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('model_used', models.CharField(choices=[('beasiswa', 'Beasiswa'), ('konsistensi', 'Konsistensi'), ('magang', 'Magang'), ('non_akademik', 'Non Akademik')], max_length=20)),
                ('input_data', models.TextField()),
                ('prediction_result', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelInfo',
        ),
    ]
